config/routes.rb
Rails.application.routes.draw do
  root to: 'users#top'

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  get 'recommend/index', to: 'recommend#index', as: 'recommends'

  resources :warning_report, only:[:index,:edit,:show,:update,:destroy]
  get 'warning_report/create/:id', to: 'warning_report#create', as: 'create_warning_report'

  get 'books/search', to: 'books#search'
  resources :books

  get 'reviews/add_bookshelf:id', to: 'reviews#add_bookshelf', as: 'add_bookshelf'
  get 'reviews/index_my_bookshelf', to: 'reviews#index_my_bookshelf', as: 'my_bookshelf'
  get 'reviews/index_search_review/:id', to: 'reviews#index_search_review', as: 'search_review'
  resources :reviews

  resources :users , only:[:show]

  #管理サイト
  get 'admins/top', to: 'admins/admins#top', as: 'admin_top'
  # get 'admins/index', to: 'admins#index', as: 'admin_index'
  # get 'admins/new', to: 'admins#new', as: 'admin_new'
  # post 'admins/create', to: 'admins#create', as: 'admin_create'
  # get 'admins/edit', to: 'admins#edit', as: 'admin_edit'
  # post 'admins/update', to: 'admins#update', as: 'admin_update'
  # delete 'admins/delete', to: 'admins#destroy', as: 'admin_destroy'

  namespace :admins do
    resources :users, only:[:index,:edit,:show,:update,:destroy]
    resources :admins
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admins/admins/edit.html.erb
<h3>Admin情報編集</h3>

<%= form_for(@admin,url: admins_admin_path,method: 'PATCH') do |f| %>

  <div class="field">
    <%= f.label 'メールアドレス' %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label 'パスワード' %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> 文字以上)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label 'パスワード 確認' %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "更新",class: 'btn small-btn orrange-btn' %>
  </div>
<% end %>

app/views/admins/admins/index.html.erb
<h4>管理ユーザー一覧</h4>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th>email</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.email %></td>
        <td><%= link_to '編集',edit_admins_admin_path(admin.id) %></td>
        <% if admin.id != current_admin.id %>
        <td><%= link_to '削除',admins_admin_path(admin.id), method: :delete, data: { confirm: 'このユーザーを削除しますか？' } %></td>
        <% else %>
        <td><%= link_to '削除','#',:disabled => true%></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to '新規登録',new_admins_admin_path, class: "btn orrange-btn" %>
<br>

app/views/admins/admins/new.html.erb
<h3>Admin新規登録</h3>

<%= form_for(@admin,url: admins_admins_path,method: 'POST') do |f| %>

  <div class="field">
    <%= f.label 'メールアドレス' %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label 'パスワード' %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> 文字以上)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label 'パスワード 確認' %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "登録",class: 'btn small-btn orrange-btn' %>
  </div>
<% end %>

app/views/admins/admins/top.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="warning_reports_summary">
      <h4>Tasks</h4>
      <div class="summary-header">
        現在の通報未対応件数
      </div>
      <div class="summary-body">
        <%= "#{@warning_reports_count} 件" %>
      </div>
    </div>
  </div>
</div>