config/routes.rb
Rails.application.routes.draw do
  root to: 'users#top'

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  get 'recommend/index', to: 'recommend#index', as: 'recommends'

  resources :warning_report, only:[:index,:edit,:show,:update,:destroy]
  get 'warning_report/create/:id', to: 'warning_report#create', as: 'create_warning_report'

  get 'books/search', to: 'books#search'
  resources :books

  get 'reviews/add_bookshelf:id', to: 'reviews#add_bookshelf', as: 'add_bookshelf'
  get 'reviews/index_my_bookshelf', to: 'reviews#index_my_bookshelf', as: 'my_bookshelf'
  get 'reviews/index_search_review/:id', to: 'reviews#index_search_review', as: 'search_review'
  resources :reviews

  resources :users , only:[:show]

  #管理サイト
  get 'admins/top', to: 'admins/admins#top', as: 'admin_top'
  # get 'admins/index', to: 'admins#index', as: 'admin_index'
  # get 'admins/new', to: 'admins#new', as: 'admin_new'
  # post 'admins/create', to: 'admins#create', as: 'admin_create'
  # get 'admins/edit', to: 'admins#edit', as: 'admin_edit'
  # post 'admins/update', to: 'admins#update', as: 'admin_update'
  # delete 'admins/delete', to: 'admins#destroy', as: 'admin_destroy'

  namespace :admins do
    resources :users, only:[:index,:edit,:show,:update,:destroy]
    resources :admins
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_mybooks
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_brank_book, only:[:index, :index_my_bookshelf,:index_search_review,:show,:edit]
  before_action :set_status, only:[:index_my_bookshelf,:edit]
  before_action :is_mine_review, only:[:edit,:update,:destory]

  # 感想の新着一覧表示(最新２０件)
  def index
    @reviews = Review.where(status_id: 3).where(private: false).order(:updated_at).reverse_order
    if !@reviews.nil?
      @reviews = Kaminari.paginate_array(@reviews).page(params[:page]).per(10)
    end
  end

  # 自分の本棚の一覧表示
  def index_my_bookshelf
    @q = Review.search(params[:q])
    @reviews = @q.result.where(user_id: current_user.id).page(params[:page]).per(10)
    set_mybooks
  end

  # 書籍検索結果からの感想一覧表示
  def index_search_review
    book = Book.find_by(tmp_id: params[:id])
    @reviews = Review.where(book_id: book.id).where(status_id: 3).where(private: false).page(params[:page]).per(10)
  end

  # 感想の詳細表示
  def show
    # 通報処理済みの場合は表示させない
    if @review.warning
      @warning = true;
    end
    # 自分の感想か、他人の感想か？
    if @review.user_id == current_user.id
      #自分の感想
    else
      mine_reviews = Review.find_by(user_id: current_user.id,book_id: @review.book.id)
      if mine_reviews.nil?
        #本棚に追加されていない状態
        @added = false
      else
        @added = true
        #読み終わっているか？
        if mine_reviews.status_id == 3
          @readed = true
        else
          @readed = false
        end
      end
    end
    @statuses = Status.all
  end

  # 使わないかもしれない
  def new
    @review = Review.new
  end

  # 感想の編集・更新
  def edit
    @book = Book.find(@review.book_id)
  end


  # 本を本棚に追加する
  # bookに情報がなければBookを新規登録する
  def add_bookshelf
    #同様の書籍がすでに本棚にある場合は登録しない
    review = Review.find_by(user_id: current_user.id, book_id: params[:id])
    if review.nil?
      review = Review.new(
        user_id: current_user.id,
        book_id: params[:id],
        status_id: 1,
        title: '',
        innocent_review: '',
        review: ''
      )
      review.save
    end
    redirect_to action: :edit,id: review.id
  end

  # 感想の編集・更新
  def update
      if @review.update(review_params)
        Recommend.update_recommend(current_user.id)
        redirect_to @review, notice: '感想を更新しました'
      else
        render :edit
      end
  end

  # 感想の破棄
  def destroy
    @review.destroy
    redirect_to reviews_url, notice: '本棚から削除しました'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end
    def set_brank_book
      @search_book = Book.new
    end
    def set_status
      @statuses = Status.all
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:user_id,
                                     :book_id,
                                     :status_id,
                                     :title,
                                     :innocent_review,
                                     :review,
                                     :private,
                                     :warning
                                   )
    end
    def set_mybooks
      @unread_books = Review.where(user_id: current_user.id).where(status_id: 1).count
      @reading_books = Review.where(user_id: current_user.id).where(status_id: 2).count
      @readed_books =  Review.where(user_id: current_user.id).where(status_id: 3).count
    end
    # 自身の感想かのフィルター
    def is_mine_review
      review = Review.find(params[:id])
      if review.user_id != current_user.id
        redirect_to root_path
      end
    end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :review_user_id %>
  </div>

  <div class="field">
    <%= form.label :book_id %>
    <%= form.text_field :book_id, id: :review_book_id %>
  </div>

  <div class="field">
    <%= form.label :status_id %>
    <%= form.text_field :status_id, id: :review_status_id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :review_title %>
  </div>

  <div class="field">
    <%= form.label :innocent_review %>
    <%= form.text_area :innocent_review, id: :review_innocent_review %>
  </div>

  <div class="field">
    <%= form.label :review %>
    <%= form.text_area :review, id: :review_review %>
  </div>

  <div class="field">
    <%= form.label :private %>
    <%= form.check_box :private, id: :review_private %>
  </div>

  <div class="field">
    <%= form.label :warning %>
    <%= form.check_box :warning, id: :review_warning %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h3>edit review</h3>
    <div class="review-header">
      書籍情報
    </div>
    <div class="review-body">
      <h4><%= @review.book.title %></h4>
      <table class="book-detail-tbl">
        <tr>
          <td>著者</td>
          <td><%= @review.book.author %></td>
          <td>出版時期</td>
          <td><%= @review.book.publication.strftime("%Y/%m") if !@review.book.publication.nil? %></td>
        </tr>
        <tr>
          <td>出版社</td>
          <td><%= @review.book.publisher %></td>
          <td>ISBN</td>
          <td><%= @review.book.isbn %></td>
        </tr>
      </table>
    </div>
  </div>
</div>
<%= form_for(@review) do |f| %>
  <div class="row">
    <div class="col-lg-12">
      <div class="review-buttons">
        <% @statuses.each do |status|%>
          <% if status.id == @review.status.id %>
            <%= f.radio_button("status_id",status.id,:checked => true)%>
          <% else %>
            <%= f.radio_button("status_id",status.id)%>
          <% end %>
          <%= f.label("status_id_#{status.id}",status.status_name,:class=>"review-radio-label")%>
        <% end %>
      </div>
    </div>
  </div>
  <% if @review.status.id == 1 %>
  <% disabled = true %>
  <% elsif %>
  <% disabled = false %>
  <% end %>
  <div class="row">
    <div class="col-lg-12">
      <div class="review-title">
        <%= f.text_field :title,:class =>'review-form',:disabled => disabled, :placeholder => "感想のタイトル" %>
      </div>
      <div class="review-header">
        ねたばれなし
      </div>
      <div class="review-body">
        <%= f.text_area :innocent_review,:class =>'review-form review-form-area',:disabled => disabled, :placeholder => "作品の核心に触れるような内容はお控えください"%>
      </div>
      <div class="review-header">
        感想
      </div>
      <div class="review-body">
        <%= f.text_area :review,:class =>'review-form review-form-area', :disabled => disabled, :placeholder => "作品の核心に触れるような内容でも記載可能な項目です"%>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="review-buttons">
      <%= f.submit '感想の更新', class: "btn orrange-btn" %>
      <%= link_to '本棚に戻る', my_bookshelf_path, class: 'btn small-btn green-btn' %>
      <%= link_to '本棚から削除する', review_path,method: 'DELETE',data: {confirm: "本当に削除しますか？"} , class: 'btn warning-btn' %>
    </div>
  </div>
<% end %>
<script>
$( 'input[name="review[status_id]"]:radio' ).change( function() {
  if ($( this ).val() == 1){
    $('.review-title > input').prop("disabled", true);
    $('.review-body > textarea').prop("disabled", true);
  }else{
    $('.review-title > input').prop("disabled", false);
    $('.review-body > textarea').prop("disabled", false);
  }
});
</script>

app/views/reviews/index.html.erb
<h3>new arrivals</h3>
<div id="box">
  <% @reviews.each do |review| %>
    <%= link_to review_path(review.id) do %>
      <div class="review">
        <div class="review-info">
          <div class="review-info-col">
            <h5> <%= review.title.truncate(27) %></h5>
            <p> - <%= review.user.nickname %></p>
            <p class="detail"> 更新日　<%= review.updated_at.strftime("%Y/%m/%d")%></p>
            <%= image_tag 'book.png', :width => '20' %>
            <p class="title"><%= review.book.title.truncate(17) %></p>
            <p>【著者】　<%= review.book.author.truncate(20) %></p>
            <p class="detail">【出版】　<%= review.book.publication.strftime("%Y/%m") if !review.book.publication.nil?  %></p>
            <p class="detail">【出版社】<%= review.book.publisher.truncate(20) %></p>
            <p class="detail">【ISBN】　<%= review.book.isbn %></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<%= paginate @reviews,window: 2 %>
<br>
<script>
// mazonryの設定
var $container = $('#box');
$container.imagesLoaded(function(){
  $('#box').masonry({
    itemSelector: '.review',
    columnWidth: 220,
    isFitWidth: true,
    horizontalOrder: true,
    gutter: 5
  });
});
</script>

app/views/reviews/index_my_bookshelf.html.erb
<h3>my bookshelf</h3>
<div class='search'>
  <%= search_form_for @q,url: my_bookshelf_path do |f| %>
    <%= f.radio_button :status_id_eq,'',:checked => true %><%= f.label 'すべて',:for => "q_status_id_eq_" %>
    <%= f.collection_radio_buttons :status_id_eq,Status.all ,:id,:status_name %>
    <%= f.submit "検索", class: "btn small-btn green-btn thin-btn" %>
  <% end %>
</div>
<div id="box">
  <% @reviews.each do |review| %>
    <%= link_to  review_path(id: review.id) do %>
      <div class="review">
        <div class="review-info">
          <div class="review-info-col">
            <p class="title"><%= review.book.title.truncate(17) %></p>
            <p>【著者】　<%= review.book.author.truncate(20) %></p>
            <p class="detail">【出版】　<%= review.book.publication.strftime("%Y/%m") if !review.book.publication.nil?  %></p>
            <p class="detail">【出版社】<%= review.book.publisher.truncate(20) %></p>
            <p class="detail">【ISBN】　<%= review.book.isbn %></p>
            <p> 状況　<%= review.status.status_name %></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<%= paginate @reviews %>
<script>
// mazonryの設定
var $container = $('#box');
$container.imagesLoaded(function(){
  $('#box').masonry({
    itemSelector: '.review',
    columnWidth: 220,
    isFitWidth: true,
    horizontalOrder: true,
    gutter: 5
  });
});
</script>

app/views/reviews/index_search_review.html.erb
<h3><%= "#{@reviews[0].book.title} の感想"%></h3>
<div id="box">
  <% @reviews.each do |review| %>
    <%= link_to review_path(review.id) do %>
      <div class="review">
        <div class="review-info">
          <div class="review-info-col">
            <h5> <%= review.title.truncate(27) %></h5>
            <p> - <%= review.user.nickname %></p>
            <p class="detail"> 更新日　<%= review.updated_at.strftime("%Y/%m/%d")%></p>
            <%= image_tag 'book.png', :width => '20' %>
            <p class="title"><%= review.book.title.truncate(17) %></p>
            <p>【著者】　<%= review.book.author.truncate(20) %></p>
            <p class="detail">【出版】　<%= review.book.publication.strftime("%Y/%m") if !review.book.publication.nil?  %></p>
            <p class="detail">【出版社】<%= review.book.publisher.truncate(20) %></p>
            <p class="detail">【ISBN】　<%= review.book.isbn %></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<%= paginate @reviews %>
<br>
<script>
// mazonryの設定
var $container = $('#box');
$container.imagesLoaded(function(){
  $('#box').masonry({
    itemSelector: '.review',
    columnWidth: 220,
    isFitWidth: true,
    horizontalOrder: true,
    gutter: 5
  });
});
</script>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="review-header">
      <%= image_tag 'book_white.png', :width => '20' %>　書籍情報
    </div>
    <div class="review-body">
      <h4><%= @review.book.title %></h4>
      <table class="book-detail-tbl nomal">
        <tr>
          <td>著者</td>
          <td><%= @review.book.author %></td>
          <td>出版時期</td>
          <td><%= @review.book.publication.strftime("%Y/%m") if !@review.book.publication.nil? %></td>
        </tr>
        <tr>
          <td>出版社</td>
          <td><%= @review.book.publisher %></td>
          <td>ISBN</td>
          <td><%= @review.book.isbn %></td>
        </tr>
      </table>
      <table class="book-detail-tbl narrow">
        <tr>
          <th>著者</th>
        </tr>
        <tr>
          <td><%= @review.book.author %></td>
        </tr>
        <tr>
          <th>出版時期</th>
        </tr>
        <tr>
          <td><%= @review.book.publication.strftime("%Y/%m") if !@review.book.publication.nil? %></td>
        </tr>
        <tr>
          <th>出版社</th>
        </tr>
        <tr>
          <td><%= @review.book.publisher %></td>
        </tr>
        <tr>
          <th>ISBN</th>
        </tr>
        <tr>
          <td><%= @review.book.isbn %></td>
        </tr>
      </table>
    </div>
  </div>
</div>
<% if @warning && @review.user.id != current_user.id %>
  <div class="row">
    <div class="col-lg-12">
      <div class="review-title center">
        <p>この感想は不適切な内容を含んでいるため非表示にされています。</p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="review-buttons">
        <%= link_to '戻る', reviews_path ,class: 'btn green-btn' %>
      </div>
    </div>
  </div>
<% else %>
  <% if @review.user.id == current_user.id %>
    <div class="row">
      <div class="col-lg-12">
        <div class="review-title">
          <h4><%= @review.status.status_name %></h4>
        </div>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="col-lg-12">
      <div class="review-title">
        <%= @review.title %>
      </div>
      <div class="review-header">
        <%= image_tag 'in_review_white.png', :width => '20' %>　ねたばれなし
      </div>
      <div class="review-body">
        <%= simple_format(h(@review.innocent_review)) %>
      </div>
      <div class="review-header">
        <%= image_tag 'review_white.png', :width => '20' %>　感想
      </div>
      <div class="review-body">
        <% if @review.user_id == current_user.id ||( @added && @readed) %>
          <%= simple_format(h(@review.review)) %>
        <% else %>
          <div class="unreaded">
            <p>まだこの本を読んでいないため、感想を見ることができません</p>
            <% if !@readed %>
              <%= link_to '本棚に追加する', add_bookshelf_path(@review.book_id), class: 'btn orrange-btn' %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="review-buttons">
      <% if @review.user.id == current_user.id %>
        <%= link_to '感想を編集する', edit_review_path(@review),class: 'btn orrange-btn' %>
      <% end %>
      <%= link_to '戻る', reviews_path ,class: 'btn green-btn small-btn' %>
      <% if @review.user.id != current_user.id %>
        <br>
        <br>
        <%= link_to create_warning_report_path(@review.id),data:{confirm:'このレビューを不適切な内容として通報しますか？'}, class: 'btn warning-btn'  do %>
          <%= image_tag 'warning_white.png', :width => '20' %>　通報する
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>