config/routes.rb
Rails.application.routes.draw do
  root to: 'users#top'

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  get 'recommend/index', to: 'recommend#index', as: 'recommends'

  resources :warning_report, only:[:index,:edit,:show,:update,:destroy]
  get 'warning_report/create/:id', to: 'warning_report#create', as: 'create_warning_report'

  get 'books/search', to: 'books#search'
  resources :books

  get 'reviews/add_bookshelf:id', to: 'reviews#add_bookshelf', as: 'add_bookshelf'
  get 'reviews/index_my_bookshelf', to: 'reviews#index_my_bookshelf', as: 'my_bookshelf'
  get 'reviews/index_search_review/:id', to: 'reviews#index_search_review', as: 'search_review'
  resources :reviews

  resources :users , only:[:show]

  #管理サイト
  get 'admins/top', to: 'admins/admins#top', as: 'admin_top'
  # get 'admins/index', to: 'admins#index', as: 'admin_index'
  # get 'admins/new', to: 'admins#new', as: 'admin_new'
  # post 'admins/create', to: 'admins#create', as: 'admin_create'
  # get 'admins/edit', to: 'admins#edit', as: 'admin_edit'
  # post 'admins/update', to: 'admins#update', as: 'admin_update'
  # delete 'admins/delete', to: 'admins#destroy', as: 'admin_destroy'

  namespace :admins do
    resources :users, only:[:index,:edit,:show,:update,:destroy]
    resources :admins
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<!--footer-->
<div class="row">
  <div class="col-lg-12">
    <div class="nomal center">サイト概要　｜　お問い合わせ　｜　<%=image_tag 'facebook_white.png',:size => "18x18",:alt => "facebook" %>　｜　<%=image_tag 'twitter_white.png',:size => "18x18",:alt => "twitter" %></div>
    <div class="narrow">
      <ul>
        <li>サイト概要</li>
        <li>お問い合わせ</li>
        <li><%=image_tag 'facebook_white.png',:size => "18x18",:alt => "facebook" %>　facebook</li>
        <li><%=image_tag 'twitter_white.png',:size => "18x18",:alt => "twitter" %>　twitter</li>
      </ul>
    </div>
    <p class="center">Copyright © 2018 honto All Rights Reserved.</p>
  </div>
</div>

app/views/layouts/admin_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>hon to admin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <header>
        <div class="row">
          <div class="col-lg-4">
            <div class="logo">
                <%= image_tag 'logo.png',:width => "80" %>
                ADMIN
            </div>
          </div>
          <% if admin_signed_in? %>
            <div class="col-lg-8 user-info">
              <%= "ログインユーザ　#{current_admin.email}　最終ログイン　#{current_admin.last_sign_in_at.strftime("%Y/%m/%d %H:%M:%S")}"%>
              <%= link_to 'ログアウト',destroy_admin_session_path, method: :delete,class: "btn small-btn thin-btn orrange-btn" %>
            </div>
          <% end %>
        </div>
      </header>
      <main>
        <div class="admin-menu">
          <div class="row">
            <% if admin_signed_in? %>
              <div class="col-lg-12">
                <%= link_to '　tasks',admin_top_path %>
                <%= link_to '　user list',admins_users_path %>
                <%= link_to '　warning reports',warning_report_index_path %>
                <%= link_to '　admin list',admins_admins_path %>
              </div>
            <% end %>
          </div>
        </div>
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value[0], class: "#{key}") %>
        <% end %>
        <%= yield %>
      </main>
      <footer>
        <%= render 'layouts/footer' %>
      </footer>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>hon to</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
  </head>
  <body>
    <div class="container-fluid">
      <header>
        <div class="row">
          <div class="col-lg-10 col-xs-8">
            <div class="logo">
                <%= image_tag 'logo.png',:width => "80" %>
            </div>
            <% if user_signed_in? %>
              <div class="books-count">
                <%= mybookshelf_books(@unread_books) %>
                <%= mybookshelf_books(@reading_books) %>
                <%= mybookshelf_books(@readed_books) %>
              </div>
            <% end %>
          </div>
          <div class="col-lg-2 col-xs-4 right">
            <% if user_signed_in? %>
              <div class="switch op"><%= image_tag 'menu.png',:width => "20" %></div>
            <% end %>
          </div>
        </div>
      </header>
      <main>
        <input id="open" type="checkbox">
        <div class="menu">
          <div class="row">
            <div class="col-lg-12">
              <p class="switch cl"><%= image_tag 'close.png',:width => "20" %></p>
              <% if user_signed_in? %>
                <%= link_to 'new arrivals',reviews_path %> <br>
                <%= link_to 'my bookshelf',my_bookshelf_path %><br>
                <%= link_to 'reccomend', recommends_path %><br>
                <%= link_to 'setting',user_path(current_user.id) %><br>
                <hr>
                <div class="search-books">
                  <%= form_for(@search_book,url: books_search_path, method: 'get') do |f| %>
                    <p>書籍検索</p>
                    <%= f.text_field :search_word %>
                    <%= f.submit '検索' , class: "btn small-btn thin-btn orrange-btn"%>
                  <% end %>
                </div>
                <hr>
                <div class="login-info">
                  <p>ログインユーザ</p>
                  <p>　<%= "#{current_user.nickname}　さん" %></p>
                  <p>最終ログイン</p>
                  <p>　<%= "#{current_user.last_sign_in_at.strftime("%Y/%m/%d %H:%M:%S")}"%></p>
                </div>
                <%= link_to 'ログアウト',destroy_user_session_path, method: :delete,class: "btn small-btn thin-btn orrange-btn" %>
              <% end %>
            </div>
          </div>
        </div>
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>
        <%= yield %>
      </main>
      <footer>
        <%= render 'layouts/footer' %>
      </footer>
    </div>
  </body>
</html>
<script>
$(function() {
  $('.switch').click(function() {
    if ($('#open').prop('checked')) {
      $("#open").prop("checked",false);
    } else {
      $("#open").prop("checked",true);
    }
  });
});
</script>